name: Deploy Altbuilda Website

on:
  push:
    branches:
      - definity

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript Files
        run: tsc

      - name: Build project
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_APP_URL: ${{ secrets.VITE_APP_URL }}
        run: npm run build

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /home2/boldbyal/public_html/
          local-dir: ./dist/
